version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Run eslint
          command: yarn lint
      - run:
          name: Compile galactica
          command: yarn build

workflows:
  sample:
    jobs:
      - build
