version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install pnpm package manager & TypeScript globally
          command: sudo npm i -g pnpm typescript
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Run eslint
          command: pnpm lint
      - run:
          name: Compile galactica
          command: pnpm build

workflows:
  sample:
    jobs:
      - build
