version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '16.16'
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Compile galactica
          command: npm run build

workflows:
  sample:
    jobs:
      - build
