version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '16.16'
      - run:
          name: Generate package-lock.json
          command: npm i --package-lock-only
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Generate prisma client
          command: npx prisma generate
      - run:
          name: Compile galactica
          command: npm run build
workflows:
  sample:
    jobs:
      - build
