version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Intall TypeScript globally
          command: npm i -g typescript
      - run:
          name: Compile galactica
          command: npm run build

workflows:
  sample:
    jobs:
      - build
