version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
          node-version: '16.16'
      - run:
          name: Ignore yarn interity checking
          command: sudo yarn config set unsafe-disable-integrity-migration true -g
      - run:
          name: Run eslint
          command: yarn lint
      - run:
          name: Compile galactica
          command: yarn build

workflows:
  sample:
    jobs:
      - build
