version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install --frozen-lockfile
      - run:
          name: Run eslint
          command: yarn lint
      - run:
          name: Compile galactica
          command: yarn build

workflows:
  sample:
    jobs:
      - build
