version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.15
    steps:
      - checkout
      - run:
          name: Generate package-lock.json
          command: npm i --package-lock-only
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Intall TypeScript globally
          command: sudo npm i -g typescript
      - run:
          name: Compile galactica
          command: npm run build

workflows:
  sample:
    jobs:
      - build
