const GALACTICA_API_PORT = Bun.env.GALACTICA_API_PORT || 3000
const GALACTICA_TOKEN = Bun.env.GALACTICA_TOKEN
const ACCESS_TOKEN_EXP = 5 * 60 // 5 minutes
const REFRESH_TOKEN_EXP = 7 * 86400 // 7 days
const JWT_SECRET = Bun.env.JWT_SECRET
const JWT_NAME = "jwt"

export {
  GALACTICA_API_PORT,
  GALACTICA_TOKEN,
  ACCESS_TOKEN_EXP,
  REFRESH_TOKEN_EXP,
  JWT_SECRET,
  JWT_NAME,
}
