name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing TypeScript globally
      run: npm install --location=global typescript

    - name: Install Packages
      run: npm install

    - name: Run eslint
      run: npm run lint
      
    - name: Generate prisma client
      run: npx prisma generate

    - name: Build TypeScript
      run: npm run build
